project:
  type: website

website:
  title: DSAN-5000: Project
  navbar:
    search: true
    logo-href: https://kclsed.org/wp-content/uploads/2020/02/3u-georgetown-university-logo-600x200-1.png

    tools: 
      - icon: github
        href: https://github.com/anly501/dsan-5000-project-bdools
    left:
      - href: ./index.qmd
        text: About Me
      - href: https://github.com/anly501/dsan-5000-project-bdools
        text: Code
      - href: https://drive.google.com/drive/folders/1-H9c243q2D5CB6wgZD7c40CGSjNJjs4s?usp=drive_link
        text: Data
      - href: ./introduction/introduction.ipynb
        text: Introduction
      - href: ./data-gathering/data-gathering.ipynb
        text: Data Gathering

      - text: Data Cleaning
      - menu: 
        - href: ./data-cleaning/data-cleaning_python.ipynb
          text: Python
        - href: ./data-cleaning/data-cleaning_r.qmd
          text: R

      - href: ./data-exploration/data-exploration.ipynb
        text: Data Exploration
      - href: ./clustering/clustering.ipynb
        text: Clustering
      - href: ./dimensionality-reduction/dimensionality-reduction.ipynb
        text: Dimensionality Reduction

      - text: Decision Trees
        menu:
        - href: ./decision-trees/classification/classification.ipynb
          text: Classification
        - href: ./decision-trees/regression/regression.ipynb
          text: Regression

      - href: ./arm/arm.ipynb
        text: ARM
      - href: ./conclusions/conclusions.ipynb
        text: Conclusions
format:
  html:
    theme: Flatly
    toc: true
    embed-resources: true
