project:
  type: website

website:
  title: DSAN 5000  Project
  navbar:
    search: true
    logo-href: https://kclsed.org/wp-content/uploads/2020/02/3u-georgetown-university-logo-600x200-1.png

    tools: 
      - icon: github
        href: https://github.com/anly501/dsan-5000-project-bdools
    left:
      - href: ./index.qmd
        text: About Me
      - href: https://github.com/anly501/dsan-5000-project-bdools
        text: Code
      - href: https://drive.google.com/drive/folders/1-H9c243q2D5CB6wgZD7c40CGSjNJjs4s?usp=drive_link
        text: Data
      - href: ./introduction/code/introduction.ipynb
        text: Introduction
      - href: ./data-gathering/code/data-gathering.ipynb
        text: Data Gathering
      - href: ./data-cleaning/code/data-cleaning_python.ipynb
        text: Data Cleaning
      - href: ./data-exploration/code/data-exploration.ipynb
        text: Data Exploration
      - href: ./naive-bayes/code/naive-bayes.ipynb
        text: Naive Bayes
      - href: ./clustering/code/clustering.ipynb
        text: Clustering
      - href: ./dimensionality-reduction/code/dimensionality-reduction.ipynb
        text: Dimensionality Reduction
      - href: ./decision-trees/code/decision_trees.ipynb
        text: Decision Trees
      - href: ./conclusions/code/conclusions.ipynb
        text: Conclusions
format:
  html:
    theme: Flatly
    toc: true
    embed-resources: true
